const DEBUG = false;

const LEVEL_ERROR = 0;
const LEVEL_WARNING = 1;
const LEVEL_INFO = 2;

const LEVEL_ERROR_COLOR = '#f44336';
const LEVEL_WARNING_COLOR = '#ffcc00';
const LEVEL_INFO_COLOR = '#00c853';

const LEVEL_ERROR_STATUS = 'bad';
const LEVEL_WARNING_STATUS = 'stranger';
const LEVEL_INFO_STATUS = 'good';

/******/
const TYPE_NO_CHANGE = 0;
const TYPE_MINOR_DOWN = 1;
const TYPE_DOWN = 2;
const TYPE_MINOR_DOWN_AFTER_UP = 3;
const TYPE_MINOR_UP_AFTER_DOWN = 4;
const TYPE_UP = 5;
const TYPE_MINOR_UP = 6;
/******/

//-- browser name constants

const BROWSER_NAME_IE = 'Internet Explorer';
const BROWSER_NAME_FF = 'Firefox';
const BROWSER_NAME_CHROME = 'Chrome';
const BROWSER_NAME_SAFARI = 'Safari';
const BROWSER_NAME_YABROWSER = 'YaBrowser';

// -- reg exp

const PARAMETER_DEEP_LINK = "?ext_referrer=";
const APP_TOKEN = 'Owmeaiaiwlsn3444_aasi344Mgoak';

const REGEX_ACT_MIN_PRICE = /window\.runParams\.actMinPrice="(.+)";/gmi;
const REGEX_ACT_MAX_PRICE = /window\.runParams\.actMaxPrice="(.+)";/gmi;
const REGEX_MIN_PRICE = /window\.runParams\.minPrice="(.+)";/gmi;
const REGEX_MAX_PRICE = /window\.runParams\.maxPrice="(.+)";/gmi;
const REGEX_BASE_CURRENCY_CODE = /window\.runParams\.baseCurrencyCode="(.+)";/gmi;
const REGEX_REGION_COUNTRY_NAME = /window\.runParams\.regionCountryName="(.+)";/gmi;
const REGEX_REGION_PROVINCE_NAME = /window\.runParams\.regionProvinceName="(.+)";/gmi;
const REGEX_REGION_CITY_NAME = /window\.runParams\.regionCityName="(.+)";/gmi;

const REGEX_ALI_PRODUCT_ID = /^\/(?:item(?:\/.*)?\/|s\/item(?:\/.*)?\/|store\/product(?:\/.*)?\/\d+_|\d+\-)([\d]+)(?:\-detail)?\.html/;
const REGEX_GEARBEST_PRODUCT_ID = /^(?:\/.*)?\/pp_([\d]+)\.html/;
const REGEX_BANG_GOOD_PRODUCT_ID = /^(?:\/.*)?\/(?:.*)?\-p\-([\d]+)\.html/;
const REGEX_BANG_GOOD_US_PRODUCT_ID = /^(?:\/.*)?\/(?:.*)?\-wp\-Usa\-([\d]+)\.html/;
const REGEX_BANG_GOOD_EU_PRODUCT_ID = /^(?:\/.*)?\/(?:.*)?\-wp\-Eu\-([\d]+)\.html/;
const REGEX_LIGHT_IN_THE_BOX_PRODUCT_ID = /^(?:\/.*)?\/(?:.*)?_p([\d]+)\.html/;
const REGEX_TOM_TOP_PRODUCT_ID = /^(?:\/.*)?\/p\-(.+)\.html/;


const CHECK_ELEMENT_ALI = '.detail-wrap';
const CHECK_ELEMENT_GEARBEST = '#js-hdAppPrice';

const CHECK_LETYSHOPS = /letyshops\.[\w]+/gmi;
const CHECK_LETYSHOPS_VIEW = /letyshops\.[\w]+\/[\w-_\/]*[view|short\-link]\/(\d+)/gmi;
const CHECK_LETYSHOPS_VIEW_ID = /(?:\d*\.)?\d+/;

const REG_URL = /(https?:\/\/[^\s]+)/g;

const COOKIE_EXTENSION_NAME = 'extensionInstalled';
const COOKIE_EXTENSION_VALUE = 1;
const COOKIE_EXTENSION_EXPIRES = 120;

const ARRAY_MERCHANTS_PRICE = [
  13366481, // aliexpress
  17289199, // tmall
  15131011, // gearbest
  15131239, // banggood
  13433222, // lightinthebox
  13083906, // miniInTheBox
  15223074 // TOMTOP
];

const ARRAY_MERCHANTS_PRICE_SELLER = [
  13366481, // aliexpress
  17289199, // tmall
];

//-- events

const COMMUNICATION_EVENT_NAME_PREFIX = 'LETYSHOPS_',

  LOGIN_TOKEN = COMMUNICATION_EVENT_NAME_PREFIX + 'LOGIN_TOKEN',
  POPUP_FIRST_OPENING_TOKEN = COMMUNICATION_EVENT_NAME_PREFIX + 'POPUP_FIRST_OPENING_TOKEN',

  CASHBACK_ACTIVATE = COMMUNICATION_EVENT_NAME_PREFIX + 'CASHBACK_ACTIVATE',
  CASHBACK_DEACTIVATE = COMMUNICATION_EVENT_NAME_PREFIX + 'CASHBACK_DEACTIVATE',
  CASHBACK_ACTIVATE_FROM_POPUP = COMMUNICATION_EVENT_NAME_PREFIX + 'CASHBACK_ACTIVATE_FROM_POPUP',
  PROMO_ACTIVATE = COMMUNICATION_EVENT_NAME_PREFIX + 'PROMO_ACTIVATE',
  PROMO = COMMUNICATION_EVENT_NAME_PREFIX + 'PROMO',

    NOTIFICATION_CASHBACK_ACTIVATE = COMMUNICATION_EVENT_NAME_PREFIX + 'NOTIFICATION_CASHBACK_ACTIVATE',
    NOTIFICATION_DISMISS = COMMUNICATION_EVENT_NAME_PREFIX + 'NOTIFICATION_DISMISS',
    USER_NOTIFICATION_DISMISS = COMMUNICATION_EVENT_NAME_PREFIX + 'USER_NOTIFICATION_DISMISS',
    NOTIFICATION_GET_INFO = COMMUNICATION_EVENT_NAME_PREFIX + 'NOTIFICATION_GET_INFO',
    NOTIFICATION_GET_PRICE = COMMUNICATION_EVENT_NAME_PREFIX + 'NOTIFICATION_GET_PRICE',
    NOTIFICATION_GET_SIMILAR_LIST = COMMUNICATION_EVENT_NAME_PREFIX + 'NOTIFICATION_GET_SIMILAR_LIST',
    SHOW_NOTIFICATION_BY_FORCE = COMMUNICATION_EVENT_NAME_PREFIX + 'SHOW_NOTIFICATION_BY_FORCE',
    CLOSE_ALL_NOTIFICATION = COMMUNICATION_EVENT_NAME_PREFIX + 'CLOSE_ALL_NOTIFICATION',
    USER_NOTIFY_GET_INFO = COMMUNICATION_EVENT_NAME_PREFIX + 'USER_NOTIFY_GET_INFO',
    UPDATE_FAVORITE_STATUS_FROM_NOTIFICATION = COMMUNICATION_EVENT_NAME_PREFIX + 'UPDATE_FAVORITE_STATUS_FROM_NOTIFICATION',
    UPDATE_FAVORITE_STATUS_FROM_BG = COMMUNICATION_EVENT_NAME_PREFIX + 'UPDATE_FAVORITE_STATUS_FROM_NOTIFICATION',
    UPDATE_MERCHANTS_HOT_PRODUCTS = COMMUNICATION_EVENT_NAME_PREFIX + 'UPDATE_MERCHANTS_HOT_PRODUCTS',
    GET_ALIEXPRESS_ORDERS = COMMUNICATION_EVENT_NAME_PREFIX + 'GET_ALIEXPRESS_ORDERS',
    RETURN_ALIEXPRESS_ORDERS = COMMUNICATION_EVENT_NAME_PREFIX + 'RETURN_ALIEXPRESS_ORDERS',
    GET_EXTENSION_INFO = COMMUNICATION_EVENT_NAME_PREFIX + 'GET_EXTENSION_INFO',
    SEND_EXTENSION_INFO = COMMUNICATION_EVENT_NAME_PREFIX + 'SEND_EXTENSION_INFO',
    GET_PAGE_INFO = COMMUNICATION_EVENT_NAME_PREFIX + 'GET_PAGE_INFO',
    GET_PAGE_COOKIES = COMMUNICATION_EVENT_NAME_PREFIX + 'GET_PAGE_COOKIES',
    SEND_GA_CID = COMMUNICATION_EVENT_NAME_PREFIX + 'SEND_GA_CID',
    SEND_LETYTOOL_EVENT = COMMUNICATION_EVENT_NAME_PREFIX + 'SEND_LETYTOOL_EVENT',
    SEND_GOOGLE_ANALYTICS = COMMUNICATION_EVENT_NAME_PREFIX + 'SEND_GOOGLE_ANALYTICS',
    SEND_ACTIVATION_DATA = COMMUNICATION_EVENT_NAME_PREFIX + 'SEND_ACTIVATION_DATA',
    SEND_THANKS_YOU_PAGE_DATA = COMMUNICATION_EVENT_NAME_PREFIX + 'SEND_THANKS_YOU_PAGE_DATA',
    SEND_PAGE_INFO = COMMUNICATION_EVENT_NAME_PREFIX + 'SEND_PAGE_INFO',
    ANIMATE_ICON = COMMUNICATION_EVENT_NAME_PREFIX + 'ANIMATE_ICON',
    OFFLINE_LIKES = COMMUNICATION_EVENT_NAME_PREFIX + 'OFFLINE_LIKES',
    SAW_REWRITE = COMMUNICATION_EVENT_NAME_PREFIX + 'SAW_REWRITE',
    SAVE_PARAMS = COMMUNICATION_EVENT_NAME_PREFIX + 'SAVE_PARAMS',
    BUTTON_UPDATE = COMMUNICATION_EVENT_NAME_PREFIX + 'BUTTON_RED',
    SET_NOTIFICATIONS_POPUP = COMMUNICATION_EVENT_NAME_PREFIX + 'SET_NOTIFICATIONS_POPUP',
    TAB_WAS_CHANGED = COMMUNICATION_EVENT_NAME_PREFIX + 'TAB_WAS_CHANGED',
    SEND_ITEM_TO_WISH_LIST = COMMUNICATION_EVENT_NAME_PREFIX + 'SEND_ITEM_TO_WISH_LIST',
    GET_PRICE_HISTORY = COMMUNICATION_EVENT_NAME_PREFIX + 'GET_PRICE_HISTORY',
    SEND_USER_SETTINGS = COMMUNICATION_EVENT_NAME_PREFIX + 'SEND_USER_SETTINGS',

// check cookies
  CHECK_MERCHANT_COOKIES = COMMUNICATION_EVENT_NAME_PREFIX + 'CHECK_MERCHANT_COOKIES',
  SET_MERCHANT_COOKIES = COMMUNICATION_EVENT_NAME_PREFIX + 'SET_MERCHANT_COOKIES',
  CLEAR_COOKIES = COMMUNICATION_EVENT_NAME_PREFIX + 'CLEAR_COOKIES',
  GET_TOKEN_COOKIES = COMMUNICATION_EVENT_NAME_PREFIX + 'GET_TOKEN_COOKIES',

  MERCHANT_SUPPRESSED = COMMUNICATION_EVENT_NAME_PREFIX + 'MERCHANT_SUPPRESSED',
  MERCHANTS_RESET = COMMUNICATION_EVENT_NAME_PREFIX + 'MERCHANTS_RESET',

  POPUP_MERCHANTS_UPDATE = COMMUNICATION_EVENT_NAME_PREFIX + 'POPUP_MERCHANTS_UPDATE',
  POPUP_TO_NOTIFICATION_TAB = COMMUNICATION_EVENT_NAME_PREFIX + 'POPUP_TO_NOTIFICATION_TAB',
  POPUP_TO_INVITATION_TAB = COMMUNICATION_EVENT_NAME_PREFIX + 'POPUP_TO_INVITATION_TAB',
  POPUP_TO_MERCHANT_CARD = COMMUNICATION_EVENT_NAME_PREFIX + 'POPUP_TO_MERCHANT_CARD',
  POPUP_INITIALIZE_FOOTER_FOR_OFFERS = COMMUNICATION_EVENT_NAME_PREFIX + 'POPUP_INITIALIZE_FOOTER_FOR_OFFERS',
  POPUP_INITIALIZE_FOOTER_FOR_STORES = COMMUNICATION_EVENT_NAME_PREFIX + 'POPUP_INITIALIZE_FOOTER_FOR_STORES',
  POPUP_UPDATE_FOOTER = COMMUNICATION_EVENT_NAME_PREFIX + 'POPUP_UPDATE_FOOTER',
  POPUP_TO_UPDATE_FAVORITE_STATUS = COMMUNICATION_EVENT_NAME_PREFIX + 'POPUP_TO_UPDATE_FAVORITE_STATUS',
  POPUP_PUSH_REVIEWED_NOTIFY = COMMUNICATION_EVENT_NAME_PREFIX + 'POPUP_PUSH_REVIEWED_NOTIFY',
  ON_USER_LOGIN = COMMUNICATION_EVENT_NAME_PREFIX + 'ON_USER_LOGIN',
  ON_USER_LOGOUT = COMMUNICATION_EVENT_NAME_PREFIX + 'ON_USER_LOGOUT',
  USER_FETCH_INFO = COMMUNICATION_EVENT_NAME_PREFIX + 'USER_FETCH_INFO',
  USER_APPLIED_LETY_CODES = COMMUNICATION_EVENT_NAME_PREFIX + 'USER_APPLIED_LETY_CODES',
  UPDATE_LETY_CODES = COMMUNICATION_EVENT_NAME_PREFIX + 'UPDATE_LETY_CODES',
  GET_INFO_MERCHANT = COMMUNICATION_EVENT_NAME_PREFIX + 'GET_INFO_MERCHANT',
  GET_INFO_USER = COMMUNICATION_EVENT_NAME_PREFIX + 'GET_INFO_USER',
  CREATE_ADVICES = COMMUNICATION_EVENT_NAME_PREFIX + 'CREATE_ADVICES',
  GET_RECOMMENDATIONS = COMMUNICATION_EVENT_NAME_PREFIX + 'GET_RECOMMENDATIONS',
  RETURN_ADVICE_LINK = COMMUNICATION_EVENT_NAME_PREFIX + 'RETURN_ADVICE_LINK',
  LOAD_USER_LANGUAGE = COMMUNICATION_EVENT_NAME_PREFIX + 'LOAD_USER_LANGUAGE',
  REFRESH_ALL = COMMUNICATION_EVENT_NAME_PREFIX + 'REFRESH_ALL';
GET_RESPONSE_URL = COMMUNICATION_EVENT_NAME_PREFIX + 'GET_RESPONSE_URL';
GET_MERCHANT_BY_ID = COMMUNICATION_EVENT_NAME_PREFIX + 'GET_MERCHANT_BY_ID';

const TAB_CHANGED = COMMUNICATION_EVENT_NAME_PREFIX + 'TAB_CHANGED',
  TAB_SET_MERCHANT_ALIAS_AND_DEEP_LINK = COMMUNICATION_EVENT_NAME_PREFIX + 'TAB_SET_MERCHANT_ALIAS_AND_DEEP_LINK',
  NOTIFICATION_ACTIVATED_DISMISS = COMMUNICATION_EVENT_NAME_PREFIX + 'NOTIFICATION_ACTIVATED_DISMISS',
  CASHBACK_ACTIVATE_AFTER_LOG_IN = COMMUNICATION_EVENT_NAME_PREFIX + 'CASHBACK_ACTIVATE_AFTER_LOG_IN',
  MERCHANT_GET_INFO = COMMUNICATION_EVENT_NAME_PREFIX + 'MERCHANT_GET_INFO',
  CHECK_BUTTON_INDICATION = COMMUNICATION_EVENT_NAME_PREFIX + 'CHECK_BUTTON_INDICATION';

//-- SIZE OF USER HISTORY

const HISIORY_LENGTH = 10,
  GLOBAL_HISTORY_LENGTH = 100;

//-- UI

const POPUP_WIDTH = 470;
const POPUP_HEIGHT = 560;

var UPDATE_INTERVAL_MERCHANT = 2 * 60 * 60 * 1000, // 2h
    UPDATE_INTERVAL_OFFERS = 15 * 60 * 1000, // 15m
    UPDATE_INTERVAL_CODES = 2 * 60 * 60 * 1000, // 2h
    UPDATE_INTERVAL_USER_AFTER_ERROR = 30 * 1000, //30s
    REQUESTS_PERIOD_IN_CASE_OF_ERROR = 60 * 1000, //1m
    PERIODIC_SHOP_VIEWED = 2 * 60 * 60 * 1000, //2h
    USER_NOTIFY_INTERVAL = 5 * 60 * 1000, //5m
    PROMO_AJAX_NOTIFY_INTERVAL = 60 * 60 * 1000, //1h
    PROMO_NOTIFY_INTERVAL = 2 * 60 * 1000, // 2m
    PROMO_NOTIFY_PERIOD = 60 * 60 * 1000,// 1h
    UPDATE_INTERVAL_ACTIVATE = 60 * 60 * 1000,// 1h
    UPDATE_INTERVAL_USER = 60 * 1000, //1 m
    UPDATE_INTERVAL_USER_NOTIFICATION = 60 * 60 * 1000, // 1h
    UPDATE_INTERVAL_FAVORITE = 2 * 60 * 60 * 1000, // 2h
    UPDATE_INTERVAL_RECOMMENDED = 5 * 60 * 1000, // 3 m
    UPDATE_INTERVAL_VIEWED = 60 * 1000, // 1 m
    UPDATE_READING_LABEL = 5000, // 5s
    UPDATE_LOG_REQUEST = 24 * 60 * 60 * 1000, // 24h
    INTERVAL_PUSH_LOG_REQUEST = 5 * 60 * 1000, // 5 m
    INTERVAL_PUSH_LOG = 60 * 1000, // 1 m
    INTERVAL_PUSH_USER_SETTINGS = 60 * 1000, // 1 m
    INTERVAL_PUSH_USER_SETTINGS_TIMER = 3 * 60 * 60 * 1000, //3h
    UPDATE_USER_PERSONAL_CASHBACK = 10 * 1000, //10 s
    UPDATE_INTERVAL_URLS = 2 * 60 * 60 * 1000, // 2h
    UPDATE_INTERVAL_SETTINGS = 2 * 60 * 60 * 1000, // 2h
    R_LIST_ADD_PERIOD = 12 * 60 * 60 * 1000,// 12h
    UPDATE_INTERVAL_INFO_HISTORY_PRICE = 10* 60 * 1000, //10m
    UPDATE_INTERVAL_INFO_SIMILAR = 10* 60 * 1000, //10m
    INTERVAL_SHOW_NOTIFICATION_MARKET = 60 * 60 * 1000, //1h
    INTERVAL_COUNT_USER_CASHBACK_RATES = 5 * 60 * 1000; //5m

//-- tab possible states

const TAB_STATE_3RD_PARTY = 0x02;
const TAB_STATE_INTERSTITIAL_REDIRECT = 0x03;

// footer state
const FOOTER_ALL_STORES = 0x01;
const FOOTER_ALL_OFFERS = 0x02;
const FOOTER_LABEL = 0;
const FOOTER_ADVICE = true;

//-- list of 3rd party affiliate links domains

const THIRD_PARTY_LINKS = [
  'event.2parale.ro',
  'www.awin1.com',
  'partners.webmasterplan.com',
  'web.epartner.es',
  'clic.reussissonsensemble.fr',
  'being.successfultogether.co.uk',
  'anrdoezrs.net',
  't.dgm-au.com',
  'google.com/aclk?sa',
  'pepperjamnetwork.com',
  'aos.prf.hn',
  'ad.zanox.com',
  'rover.ebay.com',
  'track.commissionfactory.com.au',
  'clk.tradedoubler.com',
  'tkqlhce.com',
  'partnerprogramma.bol.com',
  'tc.tradetracker.net',
  'tr.rdrtr.com',
  'lead-analytics.nl',
  'partners.adtriplex.com',
  'action.metaffiliation.com',
  'smart4ads.com',
  'gr.linkwi.se',
  'tracking.publicidees.com',
  'fls.doubleclick.net',
  'gan.doubleclick.net',
  'click.linksynergy.com',
  'v2.afilio.com.br',
  'jdoqocy.com',
  'send.onenetworkdirect.net',
  '.7eer.net',
  '.evyy.net',
  '.ojrq.net',
  'affiliate.buy.com',
  'affiliate.rakuten.com',
  'affiliates.abebooks.com',
  'affiliates.babiesrus.com',
  'affiliates.toysrus.com',
  'afsrc=1',
  'aos.prf.hn',
  'commission-junction.com',
  'dpbolvw.net',
  'dpbolvw.net',
  'google.com/aclk',
  'gopjn.com',
  'goto.orientaltrading.com',
  'goto.target.com',
  'goto.target.com/c/',
  'kqzyfj.com',
  'partners.hotwire.com',
  'pepperjamnetwork.com',
  'pjatr.com',
  'pjtra.com',
  'pntra.com',
  'pntrs.com',
  'prf.hn',
  'qksrv.net',
  'shareasale.com',
  't.dgm-au.com',
  'www.linkconnector.com',
  'apytrc.com',
  'ams.apypx.com'
];

//-- google analytics
const googleAnalyticsTID = 'UA-97996247-1',
  googleAnalyticsURL = 'https://www.google-analytics.com',
  googleAnalyticsURLBatch = googleAnalyticsURL + '/batch',
  googleAnalyticsURLCollect = googleAnalyticsURL + '/collect',
  // main extension
  gaPrefix = '/_extension/',
  gaPageShops = gaPrefix + 'shops/',
  gaPagePopup = gaPrefix + 'popup/',
  gaPageSales = gaPrefix + 'sales/',
  gaPageFriends = gaPrefix + 'friends/',
  gaPageNews = gaPrefix + 'news/',
  gaPageHistory = gaPrefix + 'history/',
  gaDisabledShop = gaPagePopup + 'no-extension/',
  // price Monitoring
  gaPrefixMonitor = '_monitor/',
  // similar
  gaPrefixSimilar = '_recommendation/',
  gaPageSimilarShow = gaPrefixSimilar + 'show/',
  // advices
  gaPrefixAdvices = '_partner_link/',
  gaPageAdvices = gaPrefixAdvices + 'show/',

  gaPageError = gaPrefix + '404/';

const aliexpressID = 13366481;
const tmallID = 17289199;

const aliexpressSharedDomains = [
  'shoppingcart.aliexpress.com',
  'my.aliexpress.com',
  'login.aliexpress.com',
  'msg.aliexpress.com',
  'trade.aliexpress.com',
  'www.aliexpress.com',
  'home.aliexpress.com',
  'star.aliexpress.com'
];
const DEFAULT_LANGUAGE = 'en';
const DEFAULT_COUNTRY = 'EN';
const CHECK_LOCALE_COOKIE = 'hl';
const HOTLINE_SHOPS = {
  287: 16410583,
  363: 17192264,
  642: 15745743,
  862: 17132443,
  1111: 17290971,
  1719: 15253632,
  2248: 17262599,
  2252: 17210208,
  2476: 17113302,
  4625: 15254345,
  6894: 17284260,
  7803: 17291704,
  8171: 17290868,
  8549: 17130302,
  10211: 15417606,
  11054: 17113297,
  11471: 17282498,
  13493: 17247018,
  14010: 17291684,
  14461: 17208001,
  14930: 16792120,
  15927: 17227794,
  16844: 17164571,
  16882: 15745606,
  17488: 17188646,
  20315: 17278493,
  20512: 17291819,
  21192: 17243096,
  21552: 17055121,
  22038: 17283677,
  22371: 17291482,
  22852: 17286926,
  23000: 17291538,
  23088: 17288681,
  23125: 17280206,
  23233: 14460040,
  23735: 17289474,
  24408: 17221696,
  25244: 17090199,
  25246: 17125737,
  25267: 17291539,
  25296: 17264048,
  25803: 17283169,
  25852: 17291735,
  26085: 17267170,
  26107: 15253615,
  26213: 17111556,
  27052: 17246981,
  27173: 17239036,
  27343: 17200754,
  27503: 17119993,
  27806: 17256363,
  27857: 17286096,
  28602: 17287224,
  29135: 17242307,
  29359: 17286089,
  30263: 17279659,
  30268: 17291485,
  30458: 16866420,
  30766: 17268073,
  31300: 17284512,
  31985: 17287910,
};

const PERMISSIONS_SEGMENTS_NEWS_TAB = {
  letyprice: ["web.letyprice_test"],
  letyclub: ["web.letyclub_pepper_users_1", "web.letyclub_test_group_1", "web.letyclub_new_november"]
};
